### ISSUE TITLE
Spread weapon doesn't aim right

### ISSUE THREAD

**Issue by ButterKane** [Rackover/TurboStrikers#8]
In strike mode, if you fire your spreading weapon while turning, the bullets will not go where you are aiming.
As it is, you have to deport your fire.

**Comment by louvenarde** [comment]
https://github.com/Rackover/TurboStrikers/issues/6

**Comment by ButterKane** [comment]
It's not exactly the same thing. Even if the mesh turns correctly, we saw in the editor that the bullet still don't fly directly where you are aiming

**Comment by louvenarde** [comment]
It's because the bullets are handled serverside and the server does not know what angle your mesh is in, because the mesh angle is not replicated

**Comment by louvenarde** [comment]
85702f2af1c127d5ac46aebf9c191ebd4ef688a8
